const state={jobs:[],job:null,artifact:null,compare:null,reviews:[],decision:null};
const $=id=>document.getElementById(id);const fmtBytes=n=>n<1e6?`${(n/1e3).toFixed(0)} KB`:`${(n/1e6).toFixed(1)} MB`;
const fmtTime=n=>{n=Number(n||0);const m=Math.floor(n/60),s=n-m*60;return `${String(m).padStart(2,'0')}:${s.toFixed(3).padStart(6,'0')}`};
async function api(url,options){const r=await fetch(url,options);const body=await r.json();if(!r.ok)throw new Error(body.error||r.statusText);return body}
async function load(){const data=await api('/api/jobs');state.jobs=data.jobs;$('jobCount').textContent=`${state.jobs.length} RUNS INDEXED`;renderJobs();if(!state.job&&state.jobs.length)selectJob(state.jobs[0])}
function renderJobs(){$('jobs').innerHTML=state.jobs.map(j=>`<div class="job ${state.job?.id===j.id?'active':''}"><button class="job-button" data-job="${j.id}"><div class="job-title">${esc(j.title)}</div><div class="job-meta">${j.artifacts.length} artifacts · ${new Date(j.modified).toLocaleString()}</div><div class="job-id">${esc(j.id)}</div></button></div>`).join('');document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>selectJob(state.jobs.find(j=>j.id===b.dataset.job)))}
async function selectJob(job){state.job=job;state.artifact=preferred(job.artifacts);state.compare=null;renderJobs();renderArtifacts();renderDetails();renderViewer();await loadReviews()}
function preferred(items){return items.find(a=>a.kind==='video'&&a.path.includes('15s'))||items.find(a=>a.kind==='video')||items.find(a=>a.kind==='image'&&a.path.includes('lookdev'))||items[0]||null}
function renderArtifacts(){$('artifacts').innerHTML=state.job.artifacts.map((a,i)=>`<button class="artifact ${state.artifact?.path===a.path?'active':''}" data-artifact="${i}"><span class="kind">${a.kind} · ${fmtBytes(a.size)}</span>${esc(a.name)}</button>`).join('');document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=()=>{state.artifact=state.job.artifacts[+b.dataset.artifact];state.compare=null;renderArtifacts();renderViewer();loadReviews()})}
function media(a,label){if(!a)return '<div class="empty">No comparison selected.</div>';const tag=a.kind==='video'?`<video src="${a.url}" controls preload="metadata"></video>`:a.kind==='image'?`<img src="${a.url}" alt="${esc(a.name)}">`:`<div class="document"><a class="button" href="${a.url}" target="_blank">Open ${esc(a.name)}</a></div>`;return `<div class="media-pane"><span class="media-label">${label}</span>${tag}</div>`}
function renderViewer(){const a=state.artifact;$('artifactKind').textContent=a?a.kind.toUpperCase():'SELECT AN ARTIFACT';$('artifactTitle').textContent=a?.name||'Field review';$('openArtifact').href=a?.url||'#';$('openArtifact').classList.toggle('disabled',!a);$('viewers').classList.toggle('compare',!!state.compare);$('viewers').innerHTML=a?media(a,'A')+(state.compare?media(state.compare,'B'):''):'<div class="empty">No review artifacts found.</div>';const videos=document.querySelectorAll('video');videos.forEach(v=>v.ontimeupdate=()=>{$('currentTime').textContent=fmtTime(v.currentTime)});populateCompare()}
function populateCompare(){const candidates=state.jobs.flatMap(j=>j.artifacts.map(a=>({...a,jobId:j.id,title:j.title}))).filter(a=>state.artifact&&a.kind===state.artifact.kind&&!(a.path===state.artifact.path&&a.jobId===state.job.id));$('compareSelect').innerHTML='<option value="">Choose an artifact…</option>'+candidates.map((a,i)=>`<option value="${i}">${esc(a.title)} — ${esc(a.name)}</option>`).join('');$('compareSelect').onchange=e=>{state.compare=e.target.value===''?null:candidates[+e.target.value];renderViewer()}}
function renderDetails(){const params=state.job.parameters||{};$('parameters').innerHTML=Object.entries(params).map(([k,v])=>`<dt>${esc(k.replaceAll('_',' '))}</dt><dd>${esc(String(v))}</dd>`).join('')||'<dt>No parameters</dt><dd>—</dd>';$('provenance').innerHTML=`<dt>seed</dt><dd>${state.job.seed}</dd><dt>quality</dt><dd>${esc(state.job.quality||'—')}</dd><dt>source</dt><dd title="${esc(state.job.source_state)}">${esc(state.job.source_state.slice(0,18))}</dd><dt>job</dt><dd title="${esc(state.job.id)}">${esc(state.job.id.slice(-16))}</dd>`}
async function loadReviews(){if(!state.job)return;const data=await api(`/api/reviews/${encodeURIComponent(state.job.study_id)}`);state.reviews=data.items.filter(i=>!state.artifact||i.artifact_path===state.artifact.path);renderReviews()}
function renderReviews(){const active=state.reviews.filter(i=>i.status!=='resolved').length;$('feedbackCount').textContent=`${active} ACTIVE`;$('feedbackItems').innerHTML=[...state.reviews].reverse().map(i=>{const responses=(i.responses||[]).map(r=>`<div class="assistant-response"><div class="feedback-meta">ASSISTANT · ${new Date(r.created_at).toLocaleString()}</div><p>${esc(r.text)}</p></div>`).join('');const result=i.result?renderResult(i.result):'';return `<article class="feedback-item ${i.status}"><div class="feedback-meta"><span class="status-tag">${esc(i.status)}</span> · ${i.decision?`<span class="decision-tag">${esc(i.decision)}</span> · `:''}${i.timecode!=null?fmtTime(i.timecode)+' · ':''}${new Date(i.created_at).toLocaleString()}</div><p>${esc(i.text)}</p>${responses}${result}<button data-resolve="${i.id}" data-status="${i.status==='resolved'?'open':'resolved'}">${i.status==='resolved'?'Reopen':'Resolve'}</button></article>`}).join('')||'<div class="empty">No notes for this artifact.</div>';document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{await api(`/api/reviews/${encodeURIComponent(state.job.study_id)}/${b.dataset.resolve}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:b.dataset.status})});loadReviews()})}
function renderResult(result){const links=(result.artifact_paths||[]).map(path=>`<a target="_blank" href="/media/${encodeURIComponent(result.job_id)}/${path.split('/').map(encodeURIComponent).join('/')}">${esc(path.split('/').pop())}</a>`).join('');return `<div class="review-result"><div class="feedback-meta">IMPLEMENTATION RESULT</div>${result.commit?`<code>${esc(result.commit)}</code>`:''}${links}</div>`}
document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{state.decision=b.dataset.decision;$('decision').value=state.decision;document.querySelectorAll('[data-decision]').forEach(x=>x.classList.toggle('active',x===b))});
$('feedbackForm').onsubmit=async e=>{e.preventDefault();if(!state.artifact)return;const video=document.querySelector('.media-pane video');const payload={study_id:state.job.study_id,job_id:state.job.id,artifact_path:state.artifact.path,kind:state.decision?'decision':'comment',decision:state.decision,text:$('feedbackText').value,timecode:$('attachTime').checked&&video?video.currentTime:null};await api('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('feedbackText').value='';state.decision=null;document.querySelectorAll('[data-decision]').forEach(x=>x.classList.remove('active'));loadReviews()};
$('compareToggle').onclick=()=>{$('compareBar').classList.toggle('hidden');$('compareToggle').classList.toggle('active')};$('refresh').onclick=load;
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}load().catch(e=>{$('jobCount').textContent=`ERROR: ${e.message}`});
